#define DEBUG_CONFIG  1

/* APP MQTT CLIENT */
#ifdef DEBUG_CONFIG
	#define CONFIG_MQTT_BROKER_CERTIFICATE  1

	#define MQTT_BROKER_URI  "matt://127.0.0.1:8384"
#else
	#define MQTT_BROKER_URI  CONFIG_MQTT_BROKER_URI
#endif

/* SGP30 */
#ifdef DEBUG_CONFIG
	#define SGP30_GPIO_SCL  16
	#define SGP30_GPIO_SDA  17
#else
	#define SGP30_GPIO_SCL  CONFIG_SGP30_GPIO_SCL
	#define SGP30_GPIO_SDA  CONFIG_SGP30_GPIO_SDA
#endif

/* APP SENSOR CO2 */
#ifdef DEBUG_CONFIG
	#define SENSOR_CO2_SAMPLE_FREQ_MS     1000
	#define SENSOR_CO2_SAMPLE_NUM         5
	#define SENSOR_CO2_SAMPLE_QUEUE_SIZE  10
	
	#define SENSOR_CO2_SAMPLE_TASK_NAME_BASE  "Sensor_CO2_Sample_Task_"
#else
	#define SENSOR_CO2_SAMPLE_FREQ_MS     CONFIG_SENSOR_CO2_SAMPLE_FREQ_MS
	#define SENSOR_CO2_SAMPLE_NUM         CONFIG_SENSOR_CO2_SAMPLE_NUM
	#define SENSOR_CO2_SAMPLE_QUEUE_SIZE  CONFIG_SENSOR_CO2_SAMPLE_QUEUE_SIZE
	
	#define SENSOR_CO2_SAMPLE_TASK_NAME_BASE  CONFIG_SENSOR_CO2_SAMPLE_TASK_NAME_BASE
	
#endif